name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Build the application
      run: |
        npm ci --legacy-peer-deps
        npm run build

    - name: Deploy to production directory
      run: |
        # Copy build artifacts to the production directory
        rm -rf /home/dev/birdseye/*
        cp -R ${{ github.workspace }}/* /home/dev/birdseye/
        
        # Restart PM2 to apply changes
        pm2 reload /home/dev/birdseye
