name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20]

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci --legacy-peer-deps

    - name: Build the application
      run: npm run build --if-present

    - name: Deploy to production directory
      run: |
        rm -rf /home/dev/birdseye/*
        cp -R ${{ github.workspace }}/* /home/dev/birdseye/

    - name: Start or Reload PM2
      run: |
        pm2 start npm --name "birdseye-app" -- start --prefix /home/dev/birdseye || pm2 reload birdseye-app
        pm2 save
